// Comprehensive translation system for UbEx (Unbelievable Experiences) in Rishikesh
// Supports 11 languages: EN, HI, RU, ZH, FR, DE, ES, IT, JA, KO, HE

export interface TranslationDict {
  [lang: string]: {
    [key: string]: string;
  };
}

export const BRAND_TAGLINE: Record<string, string> = {
  EN: "UNBELIEVABLE • EXPERIENCES",
  HI: "अविश्वसनीय • अनुभव",
  RU: "НЕВЕРОЯТНЫЕ • ВПЕЧАТЛЕНИЯ",
  ZH: "令人难以置信的 • 体验",
  FR: "EXPÉRIENCES • INCROYABLES",
  DE: "UNGLAUBLICHE • ERLEBNISSE",
  ES: "EXPERIENCIAS • INCREÍBLES",
  IT: "ESPERIENZE • INCREDIBILI",
  JA: "信じられないほどの • 体験",
  KO: "믿을 수 없는 • 경험들",
  HE: "חוויות • בלתי יאומנות"
};

export const UI_TRANSLATIONS: TranslationDict = {
  EN: {
    "Bespoke Spaces in Uttarakhand": "Bespoke Spaces in Uttarakhand",
    "Discovery Filters": "Discovery Filters",
    "Price Range": "Price Range",
    "Filter By Area": "Filter By Area",
    "Distance Filter": "Distance Filter",
    "Capacity Filter": "Capacity Filter",
    "Stay Vibe Filter": "Stay Vibe Filter",
    "Experience & Terrain Filter Tags": "Experience & Terrain Filter Tags",
    "Amenity Features Filters": "Amenity Features Filters",
    "Reset All Filters": "Reset All Filters",
    "Apply Filters": "Apply Filters",
    "Bespoke Daily Sessions": "Bespoke Daily Sessions",
    "Difficulty": "Difficulty",
    "⚡ All Levels": "⚡ All Levels",
    "🧘 Easy / Gentle": "🧘 Easy / Gentle",
    "🏃 Moderate": "🏃 Moderate",
    "🏔️ Hard/Vigorous": "🏔️ Hard/Vigorous",
    "Duration": "Duration",
    "Price": "Price",
    "Review Your Booking & Pay": "Review Your Booking & Pay",
    "Team Retreats & Offsites": "Team Retreats & Offsites",
    "Traveler Community & Events": "Traveler Community & Events",
    "Guests": "Guests",
    "Check In": "Check In",
    "Check Out": "Check Out",
    "Location": "Location",
    "Book Stay": "Book Stay",
    "Search stays or experiences...": "Search stays or experiences...",
    "Search...": "Search...",
    "What Brings You Here?": "What Brings You Here?",
    "Featured Stays": "Featured Stays",
    "View All Stays": "View All Stays",
    "EXCLUSIVE STAYS": "EXCLUSIVE STAYS",
    "Elite Rooms & Co-Livings": "Elite Rooms & Co-Livings",
    "CURATED ADVENTURES": "CURATED ADVENTURES",
    "Choose Your Next Excursion": "Choose Your Next Excursion",
    "Search stays or amenities...": "Search stays or amenities...",
    "Sort By": "Sort By",
    "✨ Recommended": "✨ Recommended",
    "💵 Price: Low to High": "💵 Price: Low to High",
    "💵 Price: High to Low": "💵 Price: High to Low",
    "⭐ Rating: High to Low": "⭐ Rating: High to Low",
    "Search activity, type, timings...": "Search activity, type, timings...",
    "Search rafting, trails, ashrams...": "Search rafting, trails, ashrams...",
    "Cart": "Cart",
    "Trips": "Trips",
    "Logout": "Logout",
    "Login": "Login"
  },
  HI: {
    "Bespoke Spaces in Uttarakhand": "उत्तराखंड में बेहतरीन विला व कमरे",
    "Discovery Filters": "खोज फ़िल्टर",
    "Price Range": "मूल्य सीमा",
    "Filter By Area": "क्षेत्र द्वारा फ़िल्टर",
    "Distance Filter": "दूरी फ़िल्टर",
    "Capacity Filter": "अतिथि क्षमता",
    "Stay Vibe Filter": "वाइब फ़िल्टर",
    "Experience & Terrain Filter Tags": "रोमांच व क्षेत्र फ़िल्टर",
    "Amenity Features Filters": "कमरे की सुविधाएं",
    "Reset All Filters": "सभी फ़िल्टर हटाएँ",
    "Apply Filters": "फ़िल्टर लागू करें",
    "Bespoke Daily Sessions": "दैनिक रोमांचक सत्र",
    "Difficulty": "कठिनाई स्तर",
    "⚡ All Levels": "⚡ सभी स्तर",
    "🧘 Easy / Gentle": "🧘 आसान",
    "🏃 Moderate": "🏃 मध्यम",
    "🏔️ Hard/Vigorous": "🏔️ कठिन",
    "Duration": "अवधि",
    "Price": "मूल्य",
    "Review Your Booking & Pay": "बुकिंग की समीक्षा और भुगतान",
    "Team Retreats & Offsites": "कॉर्पोरेट टीम रिट्रीट",
    "Traveler Community & Events": "यात्री समुदाय और कार्यक्रम",
    "Guests": "अतिथि",
    "Check In": "चेक इन",
    "Check Out": "चेक आउट",
    "Location": "स्थान",
    "Book Stay": "कमरा बुक करें",
    "Search stays or experiences...": "कमरे या रोमांचक अनुभव खोजें...",
    "Search...": "खोजें...",
    "What Brings You Here?": "आप यहाँ किस लिए आये हैं?",
    "Featured Stays": "विशेष रुप से प्रदर्शित कमरे",
    "View All Stays": "सभी कमरों को देखें",
    "EXCLUSIVE STAYS": "विशेष कमरे",
    "Elite Rooms & Co-Livings": "शानदार कमरे और को-लिविंग",
    "CURATED ADVENTURES": "चुनिंदा रोमांच",
    "Choose Your Next Excursion": "अपना अगला रोमांच चुनें",
    "Search stays or amenities...": "कमरे या सुविधाएं खोजें...",
    "Sort By": "क्रमबद्ध करें",
    "✨ Recommended": "✨ अनुशंसित",
    "💵 Price: Low to High": "💵 मूल्य: कम से अधिक",
    "💵 Price: High to Low": "💵 मूल्य: अधिक से कम",
    "⭐ Rating: High to Low": "⭐ रेटिंग: उच्च से निम्न",
    "Search activity, type, timings...": "गतिविधि, समय खोजें...",
    "Search rafting, trails, ashrams...": "रैफ्टिंग, ट्रेल्स या आश्रम खोजें...",
    "Cart": "कार्ट",
    "Trips": "यात्राएं",
    "Logout": "लॉगआउट",
    "Login": "लॉगिन"
  },
  RU: {
    "Bespoke Spaces in Uttarakhand": "Уникальные локации в Уттаракханде",
    "Discovery Filters": "Фильтры поиска",
    "Price Range": "Диапазон цен",
    "Filter By Area": "Фильтр по районам",
    "Distance Filter": "Расстояние",
    "Capacity Filter": "Количество гостей",
    "Stay Vibe Filter": "Атмосфера места",
    "Experience & Terrain Filter Tags": "Тип активности и ландшафт",
    "Amenity Features Filters": "Удобства и опции",
    "Reset All Filters": "Сбросить все",
    "Apply Filters": "Применить фильтры",
    "Bespoke Daily Sessions": "Ежедневные мероприятия",
    "Difficulty": "Сложность",
    "⚡ All Levels": "⚡ Все уровни",
    "🧘 Easy / Gentle": "🧘 Легкий",
    "🏃 Moderate": "🏃 Средний",
    "🏔️ Hard/Vigorous": "🏔️ Сложный",
    "Duration": "Длительность",
    "Price": "Цена",
    "Review Your Booking & Pay": "Проверьте детали и оплатите",
    "Team Retreats & Offsites": "Корпоративные ретриты",
    "Traveler Community & Events": "События и сообщество",
    "Guests": "Гости",
    "Check In": "Заезд",
    "Check Out": "Выезд",
    "Location": "Локация",
    "Book Stay": "Забронировать",
    "Search stays or experiences...": "Искать отели или туры...",
    "Search...": "Найти...",
    "What Brings You Here?": "Что вас интересует?",
    "Featured Stays": "Рекомендуемое жилье",
    "View All Stays": "Посмотреть всё жилье",
    "EXCLUSIVE STAYS": "ЭКСКЛЮЗИВНЫЙ ИНТЕРЬЕР",
    "Elite Rooms & Co-Livings": "Элитные номера и коливинги",
    "CURATED ADVENTURES": "ОТБОРНЫЕ ПРИКЛЮЧЕНИЯ",
    "Choose Your Next Excursion": "Выберите вашу экскурсию",
    "Search stays or amenities...": "Искать жилье или удобства...",
    "Sort By": "Сортировать",
    "✨ Recommended": "✨ Рекомендуемые",
    "💵 Price: Low to High": "💵 Сначала дешевые",
    "💵 Price: High to Low": "💵 Сначала дорогие",
    "⭐ Rating: High to Low": "⭐ С высоким рейтингом",
    "Search activity, type, timings...": "Поиск активностей и расписания...",
    "Search rafting, trails, ashrams...": "Поиск рафтинга, троп, ашрамов...",
    "Cart": "Корзина",
    "Trips": "Поездки",
    "Logout": "Выйти",
    "Login": "Войти"
  },
  ZH: {
    "Bespoke Spaces in Uttarakhand": "喜马拉雅山麓的精品住区",
    "Discovery Filters": "探索筛选条件",
    "Price Range": "价格区间",
    "Filter By Area": "按区域筛选",
    "Distance Filter": "地标距离",
    "Capacity Filter": "容纳人数",
    "Stay Vibe Filter": "空间调性",
    "Experience & Terrain Filter Tags": "体验与地貌标签",
    "Amenity Features Filters": "配套设施筛选",
    "Reset All Filters": "重置所有筛选",
    "Apply Filters": "应用筛选",
    "Bespoke Daily Sessions": "每日精选体验课",
    "Difficulty": "活动难度",
    "⚡ All Levels": "⚡ 所有级别均可",
    "🧘 Easy / Gentle": "🧘 初级/轻松",
    "🏃 Moderate": "🏃 中级/挑战",
    "🏔️ Hard/Vigorous": "🏔️ 专业/高强度",
    "Duration": "时长",
    "Price": "价格",
    "Review Your Booking & Pay": "核对行程并完成支付",
    "Team Retreats & Offsites": "企业团队团建和外企会议",
    "Traveler Community & Events": "旅行者社区与多元聚会",
    "Guests": "出行人数",
    "Check In": "入住日期",
    "Check Out": "离店日期",
    "Location": "目的地区域",
    "Book Stay": "预订住宿",
    "Search stays or experiences...": "搜索旅宿或探险活动...",
    "Search...": "搜索...",
    "What Brings You Here?": "开启您的旅行灵感",
    "Featured Stays": "精选奢潮住宿",
    "View All Stays": "查看全部房源",
    "EXCLUSIVE STAYS": "独家奢华房源",
    "Elite Rooms & Co-Livings": "精英美学套房与共生公寓",
    "CURATED ADVENTURES": "专属探索路线",
    "Choose Your Next Excursion": "挑选您的下一次出行",
    "Search stays or amenities...": "搜索住宿或房间配套...",
    "Sort By": "排序方式",
    "✨ Recommended": "✨ 官方推荐",
    "💵 Price: Low to High": "💵 价格：从低到高",
    "💵 Price: High to Low": "💵 价格：从高到低",
    "⭐ Rating: High to Low": "⭐ 好评度：从高到低",
    "Search activity, type, timings...": "搜索活动、类别、日程...",
    "Search rafting, trails, ashrams...": "搜索rafting、徒步线、静心营...",
    "Cart": "购物车",
    "Trips": "我的行程",
    "Logout": "退出登录",
    "Login": "登录"
  },
  FR: {
    "Bespoke Spaces in Uttarakhand": "Espaces sur Mesure en Uttarakhand",
    "Discovery Filters": "Filtres de Découverte",
    "Price Range": "Gamme de Prix",
    "Filter By Area": "Filtrer Par Région",
    "Distance Filter": "Filtre de Distance",
    "Capacity Filter": "Filtre de Capacité",
    "Stay Vibe Filter": "Ambiance du Séjour",
    "Experience & Terrain Filter Tags": "Tags de Terrain & Expériences",
    "Amenity Features Filters": "Équipements & Services",
    "Reset All Filters": "Réinitialiser les Filtres",
    "Apply Filters": "Appliquer les Filtres",
    "Bespoke Daily Sessions": "Sessions Quotidiennes Spéciales",
    "Difficulty": "Difficulté",
    "⚡ All Levels": "⚡ Tous Niveaux",
    "🧘 Easy / Gentle": "🧘 Facile / Doux",
    "🏃 Moderate": "🏃 Modéré",
    "🏔️ Hard/Vigorous": "🏔️ Difficile / Vigoureux",
    "Duration": "Durée",
    "Price": "Prix",
    "Review Your Booking & Pay": "Vérifier & Payer la Réservation",
    "Team Retreats & Offsites": "Séjours d'Équipe & Séminaires",
    "Traveler Community & Events": "Événements & Communauté de Voyageurs",
    "Guests": "Voyageurs",
    "Check In": "Arrivée",
    "Check Out": "Départ",
    "Location": "Lieu",
    "Book Stay": "Réserver l'Hébergement",
    "Search stays or experiences...": "Rechercher hébergements ou activités...",
    "Search...": "Recherche...",
    "What Brings You Here?": "Qu'est-ce qui vous amène?",
    "Featured Stays": "Séjours Vedettes",
    "View All Stays": "Voir Tous les Séjours",
    "EXCLUSIVE STAYS": "SÉJOURS EXCLUSIFS",
    "Elite Rooms & Co-Livings": "Chambres d'Élite & Co-Livings",
    "CURATED ADVENTURES": "AVENTURES SÉLECTIONNÉES",
    "Choose Your Next Excursion": "Choisissez Votre Prochaine Excursion",
    "Search stays or amenities...": "Rechercher hébergement ou options...",
    "Sort By": "Trier Par",
    "✨ Recommended": "✨ Recommandé",
    "💵 Price: Low to High": "💵 Prix: Croissant",
    "💵 Price: High to Low": "💵 Prix: Décroissant",
    "⭐ Rating: High to Low": "⭐ Note globale la plus haute",
    "Search activity, type, timings...": "Rechercher activité, heure...",
    "Search rafting, trails, ashrams...": "Rechercher rafting, sentiers...",
    "Cart": "Panier",
    "Trips": "Mes Voyages",
    "Logout": "Se Déconnecter",
    "Login": "Connexion"
  },
  DE: {
    "Bespoke Spaces in Uttarakhand": "Maßgeschneiderte Unterkünfte in Uttarakhand",
    "Discovery Filters": "Entdeckungsfilter",
    "Price Range": "Preisspanne",
    "Filter By Area": "Nach Gegend Filtern",
    "Distance Filter": "Entfernungsfilter",
    "Capacity Filter": "Kapazitätsfilter",
    "Stay Vibe Filter": "Unterkunftsstimmung",
    "Experience & Terrain Filter Tags": "Erlebnis- & Geländefilter",
    "Amenity Features Filters": "Ausstattungsfilter",
    "Reset All Filters": "Alle Filter zurücksetzen",
    "Apply Filters": "Filter anwenden",
    "Bespoke Daily Sessions": "Individuelle Tägliche Sessions",
    "Difficulty": "Schwierigkeit",
    "⚡ All Levels": "⚡ Alle Levels",
    "🧘 Easy / Gentle": "🧘 Leicht / Sanft",
    "🏃 Moderate": "🏃 Mittel",
    "🏔️ Hard/Vigorous": "🏔️ Schwer / Intensiv",
    "Duration": "Dauer",
    "Price": "Preis",
    "Review Your Booking & Pay": "Buchung prüfen & bezahlen",
    "Team Retreats & Offsites": "Team-Retreats & Offsites",
    "Traveler Community & Events": "Reisegemeinschaft & Events",
    "Guests": "Gäste",
    "Check In": "Check-In",
    "Check Out": "Check-Out",
    "Location": "Ort",
    "Book Stay": "Aufenthalt buchen",
    "Search stays or experiences...": "Unterkünfte oder Erlebnisse suchen...",
    "Search...": "Suchen...",
    "What Brings You Here?": "Was führt Sie zu uns?",
    "Featured Stays": "Ausgewählte Unterkünfte",
    "View All Stays": "Alle Unterkünfte anzeigen",
    "EXCLUSIVE STAYS": "EXKLUSIVE UNTERKÜNFTE",
    "Elite Rooms & Co-Livings": "Elite-Zimmer & Co-Living",
    "CURATED ADVENTURES": "ADVENTURE TOUREN",
    "Choose Your Next Excursion": "Wählen Sie Ihren nächsten Ausflug",
    "Search stays or amenities...": "Unterkünfte oder Ausstattung suchen...",
    "Sort By": "Sortieren nach",
    "✨ Recommended": "✨ Empfohlen",
    "💵 Price: Low to High": "💵 Preis: Niedrig bis hoch",
    "💵 Price: High to Low": "💵 Preis: Hoch bis niedrig",
    "⭐ Rating: High to Low": "⭐ Bewertung: Hoch bis niedrig",
    "Search activity, type, timings...": "Suche nach Aktivität, Art, Zeit...",
    "Search rafting, trails, ashrams...": "Rafting, Wanderwege, Ashrams suchen...",
    "Cart": "Warenkorb",
    "Trips": "Reisen",
    "Logout": "Abmelden",
    "Login": "Anmelden"
  },
  ES: {
    "Bespoke Spaces in Uttarakhand": "Espacios Exclusivos en Uttarakhand",
    "Discovery Filters": "Filtros de Búsqueda",
    "Price Range": "Rango de Precios",
    "Filter By Area": "Filtrar por Zona",
    "Distance Filter": "Filtro de Distancia",
    "Capacity Filter": "Filtro de Capacidad",
    "Stay Vibe Filter": "Estilo de Estadía",
    "Experience & Terrain Filter Tags": "Filtros de Terreno y Experiencias",
    "Amenity Features Filters": "Servicios y Comodidades",
    "Reset All Filters": "Reiniciar Filtros",
    "Apply Filters": "Aplicar Filtros",
    "Bespoke Daily Sessions": "Sesiones Diarias Exclusivas",
    "Difficulty": "Dificultad",
    "⚡ All Levels": "⚡ Todos los Niveles",
    "🧘 Easy / Gentle": "🧘 Fácil / Suave",
    "🏃 Moderate": "🏃 Moderado",
    "🏔️ Hard/Vigorous": "🏔️ Avanzado / Riguroso",
    "Duration": "Duración",
    "Price": "Precio",
    "Review Your Booking & Pay": "Revisar Reserva y Pagar",
    "Team Retreats & Offsites": "Retiros de Equipo y Empresas",
    "Traveler Community & Events": "Eventos y Comunidad de Viajeros",
    "Guests": "Huéspedes",
    "Check In": "Entrada",
    "Check Out": "Salida",
    "Location": "Ubicación",
    "Book Stay": "Reservar Hospedaje",
    "Search stays or experiences...": "Buscar estadías o experiencias...",
    "Search...": "Buscar...",
    "What Brings You Here?": "¿Qué te trae por aquí?",
    "Featured Stays": "Estadías Destacadas",
    "View All Stays": "Ver Todo el Hospedaje",
    "EXCLUSIVE STAYS": "HOSPEDAJES EXCLUSIVOS",
    "Elite Rooms & Co-Livings": "Habitaciones de Elite y Co-Living",
    "CURATED ADVENTURES": "AVENTURAS PREPARADAS",
    "Choose Your Next Excursion": "Elige tu Próxima Excursión",
    "Search stays or amenities...": "Buscar estadías o servicios...",
    "Sort By": "Ordenar por",
    "✨ Recommended": "✨ Recomendados",
    "💵 Price: Low to High": "💵 Precio: menor a mayor",
    "💵 Price: High to Low": "💵 Precio: mayor a menor",
    "⭐ Rating: High to Low": "⭐ Calificación más alta",
    "Search activity, type, timings...": "Buscar actividades o horarios...",
    "Search rafting, trails, ashrams...": "Rafting, caminatas o ashrams...",
    "Cart": "Carrito",
    "Trips": "Mis Viajes",
    "Logout": "Cerrar sesión",
    "Login": "Iniciar sesión"
  },
  IT: {
    "Bespoke Spaces in Uttarakhand": "Spazi Esclusivi in Uttarakhand",
    "Discovery Filters": "Filtri di Scoperta",
    "Price Range": "Fascia di Prezzo",
    "Filter By Area": "Filtra per Area",
    "Distance Filter": "Filtro Distanza",
    "Capacity Filter": "Filtro Capacità",
    "Stay Vibe Filter": "Stile del Soggiorno",
    "Experience & Terrain Filter Tags": "Tag Terreno & Esperienze",
    "Amenity Features Filters": "Servizi e Accessori",
    "Reset All Filters": "Azzera Filtri",
    "Apply Filters": "Applica Filtri",
    "Bespoke Daily Sessions": "Sessioni Giornaliere Esclusive",
    "Difficulty": "Difficoltà",
    "⚡ All Levels": "⚡ Tutti i Livelli",
    "🧘 Easy / Gentle": "🧘 Facile / Dolce",
    "🏃 Moderate": "🏃 Moderato",
    "🏔️ Hard/Vigorous": "🏔️ Difficile / Intenso",
    "Duration": "Durata",
    "Price": "Prezzo",
    "Review Your Booking & Pay": "Controlla Prenotazione & Paga",
    "Team Retreats & Offsites": "Retiri di Team & Aziendali",
    "Traveler Community & Events": "Comunità di Viaggiatori & Eventi",
    "Guests": "Ospiti",
    "Check In": "Check-In",
    "Check Out": "Check-Out",
    "Location": "Destinazione",
    "Book Stay": "Prenota Soggiorno",
    "Search stays or experiences...": "Cerca alloggi o esperienze...",
    "Search...": "Cerca...",
    "What Brings You Here?": "Cosa ti porta qui?",
    "Featured Stays": "Alloggi in Evidenza",
    "View All Stays": "Mostra Tutti gli Alloggi",
    "EXCLUSIVE STAYS": "PROPOSTE ESCLUSIVE",
    "Elite Rooms & Co-Livings": "Camere d'Elite e Co-Living",
    "CURATED ADVENTURES": "ESCURSIONI SELEZIONATE",
    "Choose Your Next Excursion": "Scegli la Tua Prossima Escursione",
    "Search stays or amenities...": "Cerca alloggi o dotazioni...",
    "Sort By": "Ordina Per",
    "✨ Recommended": "✨ Consigliati",
    "💵 Price: Low to High": "💵 Prezzo: dal più basso",
    "💵 Price: High to Low": "💵 Prezzo: dal più alto",
    "⭐ Rating: High to Low": "⭐ Voti degli Ospiti",
    "Search activity, type, timings...": "Cerca attività, orari...",
    "Search rafting, trails, ashrams...": "Cerca rafting, percorsi...",
    "Cart": "Carrello",
    "Trips": "I Miei Viaggi",
    "Logout": "Sconnetti",
    "Login": "Accedi"
  },
  JA: {
    "Bespoke Spaces in Uttarakhand": "ウッタラーカンド地方の厳選された宿",
    "Discovery Filters": "こだわり条件から探す",
    "Price Range": "価格帯",
    "Filter By Area": "エリアから探す",
    "Distance Filter": "中心地からの距離",
    "Capacity Filter": "利用人数",
    "Stay Vibe Filter": "宿の雰囲気",
    "Experience & Terrain Filter Tags": "体験・地形フィルター",
    "Amenity Features Filters": "アメニティ・設備フィルター",
    "Reset All Filters": "すべてのフィルターをクリア",
    "Apply Filters": "フィルターを適用",
    "Bespoke Daily Sessions": "毎日開催の厳選体験セッション",
    "Difficulty": "難易度レベル",
    "⚡ All Levels": "⚡ すべてのレベルに対応",
    "🧘 Easy / Gentle": "🧘 初心者向け / 優しい",
    "🏃 Moderate": "🏃 中級者向け",
    "🏔️ Hard/Vigorous": "🏔️ 上級者向け / ハード",
    "Duration": "所要時間",
    "Price": "料金",
    "Review Your Booking & Pay": "予約内容の確認とお支払い",
    "Team Retreats & Offsites": "チームオフサイト・企業合宿",
    "Traveler Community & Events": "旅行者の交流・コミュニティイベント",
    "Guests": "宿泊人数",
    "Check In": "チェックイン",
    "Check Out": "チェックアウト",
    "Location": "ロケーション",
    "Book Stay": "この宿泊を予約",
    "Search stays or experiences...": "宿または現地ツアーを検索...",
    "Search...": "検索する...",
    "What Brings You Here?": "旅の目的から選ぶ",
    "Featured Stays": "おすすめの宿泊施設",
    "View All Stays": "すべての滞在先を見る",
    "EXCLUSIVE STAYS": "厳選プレミアムステイ",
    "Elite Rooms & Co-Livings": "エリート個室・コリーヴィング宿",
    "CURATED ADVENTURES": "特別キュレーション体験",
    "Choose Your Next Excursion": "次のお出かけ先を選ぶ",
    "Search stays or amenities...": "キーワード、設備を検索...",
    "Sort By": "並び替え",
    "✨ Recommended": "✨ おすすめ順",
    "💵 Price: Low to High": "💵 料金：安い順",
    "💵 Price: High to Low": "💵 料金：高い順",
    "⭐ Rating: High to Low": "⭐ ユーザー評価：高い順",
    "Search activity, type, timings...": "セッション、時間帯などを探す...",
    "Search rafting, trails, ashrams...": "ラフティング、トレイル、アシュラム...",
    "Cart": "カート",
    "Trips": "旅程・予約",
    "Logout": "ログアウト",
    "Login": "ログイン"
  },
  KO: {
    "Bespoke Spaces in Uttarakhand": "우타라칸드의 품격 있는 맞춤 공간",
    "Discovery Filters": "필터 선택",
    "Price Range": "가격대 설정",
    "Filter By Area": "지역별 필터",
    "Distance Filter": "거리 기준",
    "Capacity Filter": "승인 숙박 인원",
    "Stay Vibe Filter": "숙소 전경 및 분위기",
    "Experience & Terrain Filter Tags": "액티비티 & 지형 필터",
    "Amenity Features Filters": "편의 시설 목록",
    "Reset All Filters": "전체 필터 초기화",
    "Apply Filters": "필터 적용하기",
    "Bespoke Daily Sessions": "요일별 특별 정규 세션",
    "Difficulty": "난이도",
    "⚡ All Levels": "⚡ 모든 등급 사용 가능",
    "🧘 Easy / Gentle": "🧘 초급 / 조용한 교감",
    "🏃 Moderate": "🏃 중급 / 활기찬 도전",
    "🏔️ Hard/Vigorous": "🏔️ 상급 / 높은 고난도",
    "Duration": "진행 시간",
    "Price": "이용 금액",
    "Review Your Booking & Pay": "예약 청구 내역서 및 결제",
    "Team Retreats & Offsites": "단체 워크숍 & 오프사이트",
    "Traveler Community & Events": "여행자 커뮤니티 네트워킹",
    "Guests": "동행 인원",
    "Check In": "체크인",
    "Check Out": "체크아웃",
    "Location": "위치 필터",
    "Book Stay": "객실 바로 예약하기",
    "Search stays or experiences...": "숙박 또는 투어 찾아보기...",
    "Search...": "검색어 입력...",
    "What Brings You Here?": "어떤 로망을 품고 오셨나요?",
    "Featured Stays": "이 주의 대표 숙박 코스",
    "View All Stays": "전체 숙박 한눈에 보기",
    "EXCLUSIVE STAYS": "스페셜 럭셔리 숙소",
    "Elite Rooms & Co-Livings": "에스닉 룸 & 코리빙 숙합",
    "CURATED ADVENTURES": "전문 테마 어드벤처",
    "Choose Your Next Excursion": "일정별 탐험지 선택하기",
    "Search stays or amenities...": "키워드, 부대시설 검색...",
    "Sort By": "안내 정렬 방식",
    "✨ Recommended": "✨ 추천순",
    "💵 Price: Low to High": "💵 가격: 저렴한 순",
    "💵 Price: High to Low": "💵 가격: 높은 가격 순",
    "⭐ Rating: High to Low": "⭐ 평점: 아주 높은 순",
    "Search activity, type, timings...": "체험 활동, 특징, 시간대...",
    "Search rafting, trails, ashrams...": "래프팅, 등산로, 명상 아슈람...",
    "Cart": "장바구니",
    "Trips": "예약 내역",
    "Logout": "로그아웃",
    "Login": "로그인"
  },
  HE: {
    "Bespoke Spaces in Uttarakhand": "מקומות אירוח ייחודיים באוטראקהאנד",
    "Discovery Filters": "מסנני גילוי וחיפוש",
    "Price Range": "טווח מחירים",
    "Filter By Area": "סינון לפי אזור",
    "Distance Filter": "מרחק ממרכז הפעילות",
    "Capacity Filter": "מספר אורחים מותר",
    "Stay Vibe Filter": "אווירת מקום האירוח",
    "Experience & Terrain Filter Tags": "תגי פעילות ושטח",
    "Amenity Features Filters": "שירותים ואביזרים נלווים",
    "Reset All Filters": "איפוס כל המסננים",
    "Apply Filters": "החל מסננים",
    "Bespoke Daily Sessions": "פעילויות יומיות מומלצות ברישיקש",
    "Difficulty": "רמת קושי",
    "⚡ All Levels": "⚡ כל הרמות והסגנונות",
    "🧘 Easy / Gentle": "🧘 קל ורגוע",
    "🏃 Moderate": "🏃 רמה בינונית",
    "🏔️ Hard/Vigorous": "🏔️ מאתגר ואינטנסיבי",
    "Duration": "משך זמן",
    "Price": "מחיר",
    "Review Your Booking & Pay": "בדיקת הזמנה ותשלום אונליין",
    "Team Retreats & Offsites": "נופש חברות וגיבוש צוותים",
    "Traveler Community & Events": "אירועי קהילה ומפגשי מטיילים",
    "Guests": "מספר נופשים",
    "Check In": "צ'ק אין (כניסה)",
    "Check Out": "צ'ק אאוט (יציאה)",
    "Location": "מיקום גאוגרפי",
    "Book Stay": "הזמינו חדר עכשיו",
    "Search stays or experiences...": "חפשו לינה או סיורים...",
    "Search...": "חיפוש...",
    "What Brings You Here?": "מה החלום שלכם ברישיקש?",
    "Featured Stays": "מקומות אירוח נבחרים",
    "View All Stays": "צפו בכל מקומות האירוח",
    "EXCLUSIVE STAYS": "מקומות אירוח בלעדיים",
    "Elite Rooms & Co-Livings": "חדרי יוקרה ומתחמי שיתוף",
    "CURATED ADVENTURES": "הרפתקאות מותאמות אישית",
    "Choose Your Next Excursion": "בחרו את המסע הבא שלכם",
    "Search stays or amenities...": "חיפוש חדר או מתקנים...",
    "Sort By": "מיון לפי",
    "✨ Recommended": "✨ מומלץ על ידינו",
    "💵 Price: Low to High": "💵 מחיר: מהנמוך לגבוה",
    "💵 Price: High to Low": "💵 מחיר: מהגבוה לנמוך",
    "⭐ Rating: High to Low": "⭐ דירוג אורחים: מהגבוה לנמוך",
    "Search activity, type, timings...": "חיפושים של סיורים וזמנים...",
    "Search rafting, trails, ashrams...": "חיפוש ראפטינג, שבילים, אשראמים...",
    "Cart": "עגלה",
    "Trips": "נסיעות",
    "Logout": "התנתק",
    "Login": "התחבר"
  }
};

export const INSTANT_MEGA_TRANSLATIONS: TranslationDict = {
  villas_title: {
    EN: "Luxury Villa",
    HI: "लक्जरी विला",
    RU: "Роскошная Вилла",
    ZH: "奢华私人美学别墅",
    FR: "Villa de Luxe",
    DE: "Luxusvilla",
    ES: "Villa de Lujo",
    IT: "Villa di Lusso",
    JA: "ラグジュアリーヴィラ",
    KO: "럭셔리 독채 빌라",
    HE: "וילת פאר"
  },
  villas_desc: {
    EN: "Premium villas, curated luxury stays and scenic experiences.",
    HI: "प्रीमियम विला, सुरुचिपूर्ण शानदार प्रवास और सुरम्य अनुभव।",
    RU: "Виллы премиум-класса, роскошный отдых и живописные виды.",
    ZH: "享有极致景观的私人别墅，专为高品质旅居和私人度假设计。",
    FR: "Villas haut de gamme, séjours exclusifs et superbes paysages.",
    DE: "Premium-Villen, erstklassige Luxusunterkünfte und herrlicher Panoramablick.",
    ES: "Villas exclusivas, hospedajes de gran lujo y paisajes imponentes.",
    IT: "Ville esclusive, soggiorni di lusso e splendidi panorami collinari.",
    JA: "厳選された高級贅沢なヴィラと絶景を楽しむ極上の体験。",
    KO: "최고의 독채 디자인 빌라, 프리미엄 휴양과 특별한 자연의 감동.",
    HE: "וילות פרימיום מעוצבת, נופש יוקרתי ברמה הגבוהה ביותר עם נוף לנהר."
  },
  family_title: {
    EN: "Family Stay",
    HI: "पारिवारिक प्रवास",
    RU: "Семейный Отель",
    ZH: "温馨亲子旅宿",
    FR: "Séjour Familial",
    DE: "Familienunterkunft",
    ES: "Estadía Familiar",
    IT: "Soggiorno Familiare",
    JA: "ファミリーステイ",
    KO: "패밀리 프렌д리 홈",
    HE: "אירוח משפחתי מפנק"
  },
  family_desc: {
    EN: "Comfortable family-friendly stays with premium hospitality.",
    HI: "प्रीमियम आतिथ्य के साथ आरामदायक पारिवारिक मित्रवत विला।",
    RU: "Комфортный отдых для всей семьи с премиальной заботой.",
    ZH: "提供高品质接待服务的家庭房型，周边活动丰富且安全便利。",
    FR: "Hébergements confortables avec une hospitalité haut de gamme, parfaits en famille.",
    DE: "Gemütliche familienfreundliche Quartiere mit erstklassiger Gastfreundschaft.",
    ES: "Estadías acogedoras diseñadas para familias con la mayor hospitalidad.",
    IT: "Spazi caldi pensati per le famiglie con ospitalità premium attenta.",
    JA: "一流のおもてなしでお迎えする、快適で家族に優しい宿泊施設。",
    KO: "가족 전용 프리미엄 가구 배치와 따뜻하고 친절한 맞춤 하우스키핑 서비스.",
    HE: "אורח נוח וביתי למשפחות מטיילות עם אירוח מכל הלב למבוגרים וילדים."
  },
  workation_title: {
    EN: "Workation Suite",
    HI: "वर्केशन सुइट",
    RU: "Воркейшн Суит",
    ZH: "数字游民工作商旅套房",
    FR: "Suite Workation",
    DE: "Workation-Suite",
    ES: "Suite para Trabajo",
    IT: "Suite Workation",
    JA: "ワーケーションスイート",
    KO: "디지털 노마드 워케이션 룸",
    HE: "סוויטות עבודה ונופש"
  },
  workation_desc: {
    EN: "Stay longer with productivity, comfort and wellness.",
    HI: "उत्पादकता, सुख और कल्याण के लिए आदर्श लंबी अवधि का प्रवास।",
    RU: "Длительное проживание с отличными условиями для продуктивной работы.",
    ZH: "配备高速网络、人体工学椅与绝佳采光，工作与身心放松两不误。",
    FR: "Combinez productivité optimale, confort moderne et rituels relaxants.",
    DE: "Dauerhaft wohnen mit perfekter Arbeitsergonomie und Fitnessmöglichkeiten.",
    ES: "Equipamiento de oficina ergonómico y gran velocidad para largas estadías.",
    IT: "Trova la concentrazione ideale grazie a connessioni veloci e quiete collinare.",
    JA: "高速ネットと快適な仕事環境、リフレッシュのためのウェルネスを完備した長期滞在向け宿。",
    KO: "초고속 스타링크 인터넷, 인체공학 스마트 가구와 평온한 자연 힐링이 함께하는 방.",
    HE: "שלבו בין פרודוקטיביות מרבית, נוחות בלתי מתפשרת וסדנאות יוגה יומיות."
  },
  backpacker_title: {
    EN: "Backpacker Dorm",
    HI: "बैकपैकर डॉर्म",
    RU: "Хостел для Бэкпекеров",
    ZH: "社交背包客青年驿站",
    FR: "Dortoir Backpacker",
    DE: "Backpacker-Dorm",
    ES: "Dormitorio Backpacker",
    IT: "Dormitorio Backpacker",
    JA: "バックパッカードミトリー",
    KO: "백패커 배낭여행자 룸",
    HE: "חדרי הוסטל למטיילים"
  },
  backpacker_desc: {
    EN: "Affordable and social experiences for global travelers.",
    HI: "वैश्विक यात्रियों के लिए बजट-अनुकूल और सामाजिक आवास।",
    RU: "Доступное жилье и новые друзья со всего мира.",
    ZH: "为全球年轻旅行者打造的高性价比、充满活力的趣味共生空间。",
    FR: "Logement abordable et occasions de rencontres pour les voyageurs solos.",
    DE: "Budgetfreundliches Co-Living für weltweite Weltenbummler und Backpacker.",
    ES: "Alojamiento con encanto y grandes eventos comunitarios para mochileros.",
    IT: "La scelta migliore per viaggiatori solitari in cerca di scambi artistici e amici.",
    JA: "世界中の旅行者と交流できる、お手頃価格でフレンドリーなドミトリー宿。",
    KO: "전 세계 장기 체류 여행자들과 소통하고 함께하는 가성비와 낭만의 숙소.",
    HE: "פתרונות לינה חברתיים במחיר נוח המאפשרים להכיר חברים ומטיילים מכל העולם."
  }
};

export function t(lang: string, phrase: string): string {
  const currentLang = (lang || "EN").toUpperCase();
  const dict = UI_TRANSLATIONS[currentLang] || UI_TRANSLATIONS["EN"];
  return dict[phrase] || phrase;
}

export function getTranslatedField(lang: string, id: string, field: string): string {
  const currentLang = (lang || "EN").toUpperCase();
  
  // Try dynamic map first (Instant translations)
  const keyMap = `${id}_${field}`;
  const directKey = INSTANT_MEGA_TRANSLATIONS[keyMap];
  if (directKey && directKey[currentLang]) {
    return directKey[currentLang];
  }
  
  // Check if it matches a general prefix key
  for (const k of Object.keys(INSTANT_MEGA_TRANSLATIONS)) {
    if (id.startsWith(k) || keyMap.includes(k)) {
      if (INSTANT_MEGA_TRANSLATIONS[k][currentLang]) {
        return INSTANT_MEGA_TRANSLATIONS[k][currentLang];
      }
    }
  }

  return "";
}
